name: .NET Core Desktop

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        configuration:
          - Debug
          - Release

    env:
      Solution_Name: Voxel Engine.sln
      Test_Project_Path: tests/Tests.VoxelEngine.csproj

    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
